version: '3.4'

services:
  auth_service_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  visit_service_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  
  gateway:
    ports:
     - "${PUERTO_GATEWAY}:80"
