version: '3.4'

services:
  auth_service_api:
    container_name: auth-service-api
    image: ${DOCKER_REGISTRY-}auth_service_api
    build:
      context: .
      dockerfile: AuthService.Api/Dockerfile

  gateway:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile


  visit_service_api:
    container_name: visit-service-api
    image: ${DOCKER_REGISTRY-}visit_service_api
    build:
      context: .
      dockerfile: VisitService.Api/Dockerfile