on:
  push:
    branches:
    - main
env:
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20231102235958.azurecr.io
  CONTAINER_APP_NAME: containerapp20231102235609
  CONTAINER_APP_RESOURCE_GROUP_NAME: containerapp20231102235609ResourceGroup
  CONTAINER_APP_CONTAINER_NAME: containerapp
jobs:
  AuthService.Api_buildImageAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.registry20231102235958_USERNAME_DC28 }}
        password: ${{ secrets.registry20231102235958_PASSWORD_DC28 }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/authservice.api:${{ github.sha }}
        file: AuthService.Api\Dockerfile
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.containerapp20231102235609_SPN }}
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.registry20231102235958_USERNAME_0E21 }} --password ${{ secrets.registry20231102235958_PASSWORD_0E21 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/authservice.api:${{ github.sha }}
    - name: Azure logout
      run: az logout
  Gateway.Api_buildImageAndDeploy:
    runs-on: ubuntu-latest
    needs: AuthService.Api_buildImageAndDeploy
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.registry20231102235958_USERNAME_0E21 }}
        password: ${{ secrets.registry20231102235958_PASSWORD_0E21 }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/gateway.api:${{ github.sha }}
        file: Gateway.Api\Dockerfile
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.containerapp20231102235609_SPN }}
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.registry20231102235958_USERNAME_0E21 }} --password ${{ secrets.registry20231102235958_PASSWORD_0E21 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/gateway.api:${{ github.sha }}
    - name: Azure logout
      run: az logout
  VisitService.Api_buildImageAndDeploy:
    runs-on: ubuntu-latest
    needs: Gateway.Api_buildImageAndDeploy
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.registry20231102235958_USERNAME_0E21 }}
        password: ${{ secrets.registry20231102235958_PASSWORD_0E21 }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/visitservice.api:${{ github.sha }}
        file: VisitService.Api\Dockerfile
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.containerapp20231102235609_SPN }}
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.registry20231102235958_USERNAME_0E21 }} --password ${{ secrets.registry20231102235958_PASSWORD_0E21 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/visitservice.api:${{ github.sha }}
    - name: Azure logout
      run: az logout
